<?php declare(strict_types=1);
namespace Helmich\TypoScriptLint\Linter\ReportPrinter;

use DOMDocument;
use Helmich\TypoScriptLint\Application;
use Helmich\TypoScriptLint\Linter\Report\Report;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Report printer that generates XML documents as generated by checkstyle [1].
 *
 * These reports are well-suited for being used in continuous integration
 * environments like Jenkins [2].
 *
 * [1] http://checkstyle.sourceforge.net/
 * [2] http://jenkins-ci.org/
 *
 * @package    Helmich\TypoScriptLint
 * @subpackage Linter\ReportPrinter
 */
class CheckstyleReportPrinter implements Printer
{

    /**
     * Constructs a new checkstyle report printer.
     */
    public function __construct(private OutputInterface $output)
    {
    }

    /**
     * Writes a report in checkstyle XML format.
     *
     * @param Report $report The report to print.
     */
    public function writeReport(Report $report): void
    {
        $xml = new DOMDocument('1.0', 'UTF-8');

        $root = $xml->createElement('checkstyle');
        $root->setAttribute('version', Application::APP_NAME . '-' . Application::APP_VERSION);

        foreach ($report->getFiles() as $file) {
            $xmlFile = $xml->createElement('file');
            $xmlFile->setAttribute('name', $file->getFilename());

            foreach ($file->getIssues() as $issue) {
                $xmlWarning = $xml->createElement('error');
                $xmlWarning->setAttribute('line', $issue->getLine() ? ((string) $issue->getLine()) : "");
                $xmlWarning->setAttribute('severity', $issue->getSeverity());
                $xmlWarning->setAttribute('message', $issue->getMessage());
                $xmlWarning->setAttribute('source', $issue->getSource());

                $column = $issue->getColumn();
                if ($column !== null) {
                    $xmlWarning->setAttribute('column', "" . $column);
                }

                $xmlFile->appendChild($xmlWarning);
            }

            $root->appendChild($xmlFile);
        }

        $xml->appendChild($root);
        $xml->formatOutput = true;

        $this->output->write($xml->saveXML());
    }
}
